title: Openflexure microscope
description: An open-source 3D printable microscope, complete with high-precision XYZ stage.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

plugins:
  - jekyll-redirect-from